#!/bin/bash

RUN_ID=$1
JOB_ID=$2
SRC_URL=$3
DEST_URL=$4

shift 4
INPUT_FILES=$@

for i in lib/ebe-osg.tar.gz ${INPUT_FILES[@]}; do
  globus-url-copy \
    -verbose \
    -create-dest \
    -restart \
    -rst-retries 5 \
    -rst-interval 30 \
    -rst-timeout 30 \
    $SRC_URL/$i $(basename $i) || \
  globus-url-copy \
    -verbose \
    -create-dest \
    -restart \
    -rst-retries 5 \
    -rst-interval 30 \
    -rst-timeout 30 \
    -no-data-channel-authentication \
    -no-third-party-transfers \
    $SRC_URL/$i $(basename $i) || return 1
done


tar xzf ebe-osg.tar.gz

echo -e "run_id:  $RUN_ID\njob_id:  $JOB_ID"

./run-ebe `for F in ${INPUT_FILES[@]}; do basename $F; done`


cd results
for i in *; do
  mv $i ${JOB_ID}.${i}
done

dest="$DEST_URL/$RUN_ID"

globus-url-copy \
  -verbose \
  -create-dest \
  -parallel 4 \
  -restart \
  -rst-retries 5 \
  -rst-interval 30 \
  -rst-timeout 30 \
  '*' $dest/ || \
globus-url-copy \
  -verbose \
  -create-dest \
  -restart \
  -rst-retries 5 \
  -rst-interval 30 \
  -rst-timeout 30 \
  -no-data-channel-authentication \
  -no-third-party-transfers \
  '*' $dest/ || return 1
