#!/bin/bash


#
# startup
#


# output functions
source msg

# parses standard .ini config files
# returns key=value pairs for the desired section
# $1 = filename
# $2 = section
parse_ini () {
  sed -e 's/[[:space:]]*\=[[:space:]]*/=/g' \
    -e 's/;.*$//' \
    -e 's/[[:space:]]*$//' \
    -e 's/^[[:space:]]*//' \
    < $1 \
    | sed -n -e "/^\[$2\]/I,/^\s*\[/{/^[^;].*\=.*/p;}"
}




msg 'starting event[s]...'


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# read parameters from input files
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #



echo
msg 'reading input files'

# init. arrays to hold superMC, VISHNew, iSS settings
smc=()
vsn=()
iss=()

# read each input file
for file in $@; do
  msg2 "$file"

  # append settings from ini sections to corresponding arrays
  smc=(${smc[@]} $(parse_ini $file 'superMC'))
  vsn=(${vsn[@]} $(parse_ini $file 'VISHNew'))
  iss=(${iss[@]} $(parse_ini $file 'iSS'))
done


echo
msg 'detected settings'
msg2 "superMC:  ${smc[*]}"
msg2 "VISHNew:  ${vsn[*]}"
msg2 "iSS:      ${iss[*]}"




# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# event-by-event
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


echo
msg 'generating initial condition[s]'

cd superMC 

time ./superMC ${smc[@]} || {
  error 'superMC failed, exiting'
  exit 1 
}

nev=$(ls data/sd_event_*_block.dat | wc -l)
nsuccess=0
echo
msg "$nev ICs generated"

cd ..


# do the remaining EbE routines for each generated IC
for (( i=0; i<$nev; i++ )); do

  echo
  msg "starting event $i"


  echo
  msg 'moving IC for input to hydro'
  mv -v superMC/data/sd_event_$[$i+1]_block.dat VISHNew/Initial/InitialSd.dat


  echo
  msg 'running hydro'
  cd VISHNew 
  time ./VISHNew ${vsn[@]} || {
    warning "VISHnew failed for event ${i}, skipping to next event"
    continue 
  }
  cd ..


  echo
  msg 'moving hypersurface files for input to sampler'
  mv -v VISHNew/results/{decdat2.dat,decdat_mu.dat,surface.dat} iSS/results/


  echo
  msg 'running freeze-out hypersurface sampler'
  cd iSS 
  time ./iSS ${iss[@]} || {
    warning "iSS failed for event ${i}, skipping to next event"
    continue 
  }
  cd ..


  echo
  msg 'moving OSCAR output for input to UrQMD converter'
  mv -v iSS/OSCAR.DAT osc2u/


  echo
  msg 'running OSCAR to UrQMD converter'
  cd osc2u 
  time ./osc2u < OSCAR.DAT || {
    warning "osc2u failed for event ${i}, skipping to next event" 
    continue 
  }
  cd ..


  echo
  msg 'moving osc2u fortran output for input to UrQMD'
  mv -v osc2u/fort.14 urqmd/initial.f14ex



  echo
  msg 'running UrQMD'

  cd urqmd
  export ftn09=uqmd.burner
  export ftn10=initial.f14ex
  export ftn13=$i.f13
  time ./urqmd || {
    warning "UrQMD failed for event ${i}, skipping to next event"
    continue
  }

  echo
  msg 'checking integrity'
  nparticles=$(awk '/^ +[0-9]+ +[0-9]+$/ {print $1}' $ftn13)
  nlines=$(wc -l $ftn13 | cut -d' ' -f1)
  msg2 "event reports $nparticles particles"
  msg2 "file has $nlines lines"
  if [[ $nlines == $[$nparticles+16] ]]; then
    msg2 'verified, compressing output'
    gzip -vc $ftn13 > ../results/$ftn13.gz
    nsuccess=$[$nsuccess+1]
  else
    warning 'failed integrity check, skipping to next event'
    continue
  fi

  cd ..


  echo
  msg 'cleaning up'
  rm -v VISHNew/{Initial,results}/* iSS/results/* urqmd/initial.f14ex

done


echo
msg "${nsuccess}/${nev} events were successful"
